name: Elixir CI
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.19.1 # Define the elixir version [required]
        otp-version: 28 # Define the OTP version [required]

    - name: Install Dependencies
      run: mix deps.get

    - name: Build
      run: mix compile

    - name: Create Docs
      run: mix docs

    - name: Run Tests
      run: mix coveralls.github

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: doc
