name: Elixir CI
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # variável para testes e runtime

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Elixir and Erlang
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.19.1
        otp-version: 28.1
        install-hex: true
        install-rebar: true

    - name: Install Dependencies
      run: mix deps.get

    - name: Build
      run: mix compile

    - name: Create Docs
      env:
        MIX_ENV: dev
      run: mix docs

    - name: Run Tests
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # garante acesso à chave nos testes
      run: mix coveralls.github

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: doc
